apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/your-user/aws-eks-argocd-cicd.git"
    targetRevision: HEAD
    path: "manifests"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: "default"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
